# Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

import fnmatch
from dataclasses import dataclass, field
from typing import Callable, Optional, Tuple, Union

import torch

from ..utils import is_te_min_version


@dataclass(frozen=True)
class ParamPredicate:
    """Wraps a matching function to make it hashable for ParamKey.
    Example:
        >>> shape_1_param = ParamPredicate(name="s1", fn=lambda param: len(param.shape) == 1)
        >>> shape_1_param(torch.empty(10))
        True
        >>> shape_1_param_copy = ParamPredicate(name="s1", fn=lambda param: len(param.shape) == 1)
        >>> shape_1_param == shape_1_param_copy  # name is used to match
        True
        >>> {shape_1_param, shape_1_param_copy} == {shape_1_param}  # set hashing works properly

    NOTE:
        __hash__ and __eq__ are automatically generated by @dataclass(frozen=True)
        based solely on 'name' because we set compare=False/hash=False on 'fn'.
    """

    name: str
    fn: Callable[[torch.nn.Parameter], bool] = field(compare=False, hash=False)

    def __call__(self, param: torch.nn.Parameter) -> bool:
        return self.fn(param)


@dataclass(frozen=True)
class ParamWithNamePredicate:
    """Wraps a matching function to make it hashable for ParamKey.
    Example:
        >>> shape_1_not_qkln_param = ParamWithNamePredicate(
                name="s1_not_qkln",
                fn=lambda param, name: (
                    len(param.shape) == 1 or name.endswith(".bias")
                    and not ("q_layernorm." in name or "k_layernorm." in name)
                )
            )
        >>> shape_1_not_qkln_param(torch.empty(10), "interesting.bias")
        True
        >>> shape_1_not_qkln_param(torch.empty(10), "interesting.q_layernorm.bias")
        False

    NOTE:
        __hash__ and __eq__ are automatically generated by @dataclass(frozen=True)
        based solely on 'name' because we set compare=False/hash=False on 'fn'.
    """

    name: str
    fn: Callable[[torch.nn.Parameter, str], bool] = field(compare=False, hash=False)

    def __call__(self, param: torch.nn.Parameter, name: str) -> bool:
        return self.fn(param, name)


@dataclass(frozen=True, slots=True)
class ParamKey:
    """Key to group parameters by. All such grouped parameters can share an
    optimizer config specification."""

    # TODO: Can add layer_id here later.

    name: Union[str, Tuple[str]] = field(default_factory=tuple)
    """Parameter name(s), will use unix filesystem path syntax for matching."""

    attr: Union[str, Tuple[str]] = field(default_factory=tuple)
    """Parameter attribute(s)."""

    predicate: Union[ParamPredicate, Tuple[ParamPredicate]] = field(default_factory=tuple)
    """Predicate(s) to match parameters by. If multiple predicates are provided, any must match."""

    with_name_predicate: Union[ParamWithNamePredicate, Tuple[ParamWithNamePredicate]] = field(
        default_factory=tuple
    )
    """
    Predicate(s) to match parameters with their name. If multiple predicates are provided, 
      any must match. This is useful if you need to filter out some parameters from an otherwise 
      positive match by their name.
    """

    def matches(self, param: torch.nn.Parameter, param_name: str) -> bool:
        """Returns true if passed-in parameter (with name) matches `param_key`.

        Args:
            param (torch.nn.Parameter): Handle to parameter object.
            param_name (str): Name of parameter in underlying PyTorch module.

        Returns:
            bool: True if parameter matches passed-in param_key.
        """

        # Check if name matches.
        if isinstance(self.name, str):
            target_names = [self.name]
        else:
            target_names = list(self.name)
        for target_name in target_names:
            if fnmatch.fnmatch(param_name, target_name):
                return True

        # Check if attribute matches.
        if isinstance(self.attr, str):
            target_attrs = [self.attr]
        else:
            target_attrs = list(self.attr)
        for target_attr in target_attrs:
            if getattr(param, target_attr, False):
                return True

        # Check if predicate matches.
        if isinstance(self.predicate, ParamPredicate):
            if self.predicate(param):
                return True
        else:
            for predicate in self.predicate:
                if predicate(param):
                    return True

        # Check if with_name_predicate matches.
        if isinstance(self.with_name_predicate, ParamWithNamePredicate):
            if self.with_name_predicate(param, param_name):
                return True
        else:
            for predicate in self.with_name_predicate:
                if predicate(param, param_name):
                    return True
        return False


@dataclass
class OptimizerConfig:
    """Configuration object for Megatron optimizers."""

    ##############
    # General
    ##############

    lr: Optional[float] = None
    """Initial learning rate. Depending on decay style and initial warmup, the learning rate at each
       iteration would be different.
    """

    min_lr: Optional[float] = None
    """Minumum value for learning rate. The scheduler clip values below this threshold."""

    decoupled_lr: Optional[float] = None
    """Separate learning rate for the input and output layer."""

    decoupled_min_lr: Optional[float] = None
    """Minimum value for learning rate for the input and output layer. The scheduler clip values
       below this threshold.
    """

    weight_decay: float = 0.01
    """Weight decay coefficient for L2 regularization."""

    apply_wd_to_qk_layernorm: bool = False
    """If true, apply weight decay to qk layernorm as a special case."""

    ##############
    # Precision
    ##############
    fp8_recipe: Optional[str] = None
    """The type of fp8 recipe will affect the processing logic inside distributed optimizer."""

    fp16: bool = False
    """If true, train with fp16 mixed precision training. Defaults to False."""

    bf16: bool = False
    """If true, train with bf16 mixed precision training. Defaults to False."""

    reuse_grad_buf_for_mxfp8_param_ag: bool = False
    """If true, reuse the grad buffer for param AG when using mxfp8 recipe. Should be 
       set to True only when fp8_recipe is mxfp8 and fp8_param_gather is True."""

    params_dtype: torch.dtype = torch.float32
    """dtype used when intializing the weights. Defaults to torch.float32."""

    use_precision_aware_optimizer: bool = False
    """If true, allows optimizer-related tensors (master_param, gradients and optimizer states)
    to be set to lower precision. Defaults to False.
    """

    store_param_remainders: bool = True
    """If true, store the 16-bit FP32 parameter remainders in the optimizer state, excluding the
        16 bits shared with the BF16 parameters. This lowers GPU memory usage. Defaults to True.
    """

    main_grads_dtype: torch.dtype = torch.float32
    """dtype of main grads when enabling precision-aware-optimizer"""

    main_params_dtype: torch.dtype = torch.float32
    """dtype of main params when enabling precision-aware-optimizer"""

    exp_avg_dtype: torch.dtype = torch.float32
    """dtype of exp_avg when enabling precision-aware-optimizer"""

    exp_avg_sq_dtype: torch.dtype = torch.float32
    """dtype of exp_avg_sq when enabling precision-aware-optimizer"""

    optimizer: str = 'adam'
    """Optimizer name (e.g., 'adam', 'sgd', 'muon'). Can be overridden per-parameter group
    via config_overrides to use different optimizers for different parameters."""

    ###############
    # Loss scaling
    ###############
    loss_scale: Optional[float] = None
    """Static loss scaling, positive power of 2 values can improve fp16 convergence. If None,
       dynamic loss scaling is used.
    """

    initial_loss_scale: float = 2**32
    """Initial loss-scale for dynamic loss scaling."""

    min_loss_scale: float = 1.0
    """Minimum loss scale for dynamic loss scaling."""

    loss_scale_window: float = 1000
    """Window over which to raise/lower dynamic scale."""

    hysteresis: int = 2
    """Hysteresis for dynamic loss scaling."""

    ###################################################################################
    # Optimizer-specific parameters.
    ###################################################################################
    # Adam.
    adam_beta1: float = 0.9
    """First coefficient for computing running averages of gradient and its square in Adam
    optimizer.
    """

    adam_beta2: float = 0.999
    """Second coefficient for computing running averages of gradient and its square in Adam
    optimizer.
    """

    adam_eps: float = 1e-08
    """Term added to the denominator to improve numerical stability in Adam optimizer."""

    decoupled_weight_decay: bool = True
    """If true, decouples weight decay from the gradient update, equivalent to AdamW. If false,
    original Adam update rule will be used. Defaults to True.
    """

    # SGD.
    sgd_momentum: float = 0.9
    """Momentum factor for SGD optimizer."""

    # emerging optimizers.
    muon_momentum: float = 0.95
    """The momentum used by the internal SGD in Muon optimizer."""

    muon_split_qkv: bool = True
    """Whether to split QKV parameters for Muon optimizer."""

    muon_nesterov: bool = False
    """Whether to use Nesterov-style momentum in the internal SGD."""

    muon_scale_mode: str = "spectral"
    """The mode to use for the scale factor. Defaults to "spectral"."""

    muon_fp32_matmul_prec: str = "medium"
    """The precision to use for the fp32 matmul. Defaults to "medium"."""

    muon_coefficient_type: str = "quintic"
    """Newton-Schulz coefficient type for the Muon optimizer. Valid types are discovered
    dynamically from the installed ``emerging_optimizers`` package. Defaults to "quintic"."""

    muon_num_ns_steps: int = 5
    """The number of iteration steps to use in the Newton-Schulz iteration."""

    muon_tp_mode: str = "blockwise"
    """How to perform NS calculation for tensor parallel weights. Defaults to "blockwise"."""

    muon_extra_scale_factor: float = 1.0
    """Additional scale factor for the muon update."""

    muon_use_syrk: bool = False
    """If true, use the Triton SYRK Newton-Schulz kernels when supported."""

    muon_scalar_optimizer: str = 'adam'
    """Optimizer for nonlinear parameters (embeddings, biases, norms) when using muon.
    One of 'adam' or 'lion'. Defaults to 'adam'."""

    muon_fsdp_batched_all_gather: bool = False
    """If True, batch Muon+M-FSDP boundary parameter all-gathers by dtype/device/group. This reduces
    collective count but increases temporary peak memory. Defaults to False.
    """

    muon_fsdp_flat_batched_all_gather: bool = False
    """If True, use a flattened one-collective Muon+M-FSDP batched gather for eligible multi-stage
    shard layouts. Defaults to False.
    """

    muon_fsdp_flat_batched_all_gather_nonempty_group: bool = False
    """If True, eligible flat Muon+M-FSDP boundary gathers use a subgroup containing only ranks
    with nonempty flat chunks. Defaults to False.
    """

    muon_fsdp_reuse_gather_scratch: bool = False
    """If True, cache and reuse Muon+M-FSDP gather scratch buffers. Defaults to False."""

    muon_fsdp_padded_all_gather: bool = False
    """If True, use padded equal-size all_gather_into_tensor for Muon+M-FSDP batched gathers when
    padding overhead is within the configured threshold. Defaults to False.
    """

    muon_fsdp_padded_all_gather_pad_factor: float = 1.25
    """Maximum padded-gather size as a multiple of the uneven gathered size."""

    muon_fsdp_batch_max_gather_bytes: int = 1024 * 1024 * 1024
    """Maximum gathered bytes per Muon+M-FSDP batched gather stage."""

    muon_fsdp_padded_all_gather_zero_pad: bool = True
    """If True, zero-fill unused padding before Muon+M-FSDP padded gathers."""

    muon_fsdp_fused_async_gather_repack: bool = False
    """If True, overlapped multi-stage Muon+M-FSDP gathers repack directly from the previous
    stage's rank buffers into the next stage's send buffer. This preserves collective order and
    optimizer math while avoiding per-item intermediate unpack buffers.
    """

    muon_fsdp_boundary_pre_ns_into_gather_buffer: bool = False
    """If True, compute exact gather-mode boundary pre-Newton-Schulz tensors directly into the
    stage-0 Muon+M-FSDP gather send buffer when the wire dtype matches the local momentum dtype.
    This preserves optimizer math and removes the separate per-item pre-NS materialization plus
    stage-0 pack copy for eligible overlapped boundary gathers. Defaults to False.
    """

    muon_fsdp_boundary_batch_sort_by_size: bool = False
    """If True, deterministically launch larger Muon+M-FSDP boundary gather batches first within
    each identical communicator/stage group. This preserves per-communicator collective order and
    only changes scheduling.
    """

    muon_fsdp_fast_reconstruct: bool = True
    """If True, view contiguous gathered Muon+M-FSDP buffers without an additional reconstruction
    copy.
    """

    muon_fsdp_boundary_gather_dtype: str = 'fp32'
    """Communication dtype for Muon+M-FSDP boundary pre-NS all-gathers. Valid values are
    'fp32', 'bf16', 'int8', 'fp8_e4m3fn', and 'fp8_e5m2'. The gathered tensor is converted
    back to the local pre-NS dtype before Newton-Schulz. The int8 and fp8 modes use a
    symmetric per-batch scale.
    """

    muon_fsdp_distributed_ns: bool = False
    """If True, use distributed Newton-Schulz over eligible FSDP row shards instead of gathering
    the full Muon update first.
    """

    muon_fsdp_distributed_ns_min_numel: int = 0
    """Minimum full parameter numel required to use Muon+M-FSDP distributed Newton-Schulz.
    A value of 0 applies distributed NS to every eligible boundary parameter when enabled.
    """

    muon_fsdp_distributed_ns_small_col_dim: int = 0
    """When positive, also use distributed Newton-Schulz for eligible row-sharded boundary
    parameters whose column dimension is at most this value, even if they are below
    muon_fsdp_distributed_ns_min_numel.
    """

    muon_fsdp_distributed_ns_single_all_reduce: bool = False
    """If True, use a one-all-reduce Gram recurrence for eligible Muon+M-FSDP distributed
    Newton-Schulz chunks.
    """

    muon_fsdp_distributed_ns_gram_refresh_interval: int = 1
    """Refresh the distributed Newton-Schulz Gram all-reduce every N steps. A value of 1
    preserves the exact per-step all-reduce path.
    """

    muon_fsdp_distributed_ns_exclude_qkv: bool = False
    """If True, keep split-QKV tensors on the boundary all-gather path even when their
    shape and size would otherwise be eligible for distributed Newton-Schulz.
    """

    muon_fsdp_distributed_ns_nonempty_group: bool = False
    """If True, distributed Newton-Schulz all-reduces use a cached subgroup containing only
    ranks with nonempty FSDP shards for the parameter. Empty ranks skip the exact zero
    contribution instead of joining the Gram all-reduce.
    """

    muon_fsdp_partial_distributed_ns: bool = False
    """If True, exact mixed-shard Muon tensors may gather only the non-Newton-Schulz
    matrix dimension and then run distributed Newton-Schulz over the remaining shard
    dimension. Defaults to False.
    """

    muon_fsdp_defer_distributed_ns_under_gather: bool = False
    """If True, do not run distributed Newton-Schulz while overlapped Muon+M-FSDP
    boundary all-gathers are pending.
    """

    muon_fsdp_defer_partial_distributed_ns_under_gather: bool = False
    """If True, defer only partial-distributed Newton-Schulz while boundary
    all-gathers are pending. Ordinary distributed Newton-Schulz still runs under
    the gather, preserving the current local+distributed ordering.
    """

    muon_fsdp_async_partial_distributed_gather: bool = False
    """If True, start deferred partial-distributed gathers before local/distributed
    under-gather work and finish only their Newton-Schulz/update after the boundary
    drain. This preserves exact Muon math and only changes scheduling.
    """

    muon_fsdp_prioritize_distributed_ns: bool = False
    """If True, enqueue exact distributed Newton-Schulz batches before local Muon
    batches. This preserves update math and only changes scheduling across
    independent parameters.
    """

    muon_fsdp_approx_distributed_ns_update: bool = False
    """If True with approximate local boundary updates, route otherwise eligible
    distributed Newton-Schulz tensors to the local-boundary approximation path.
    This changes optimizer math and is intended for throughput experiments.
    """

    muon_fsdp_approx_local_boundary_update: bool = False
    """If True, approximate Muon+M-FSDP boundary updates by orthogonalizing local
    boundary shards without gathering the full tensor. This changes optimizer math
    and defaults to False.
    """

    muon_fsdp_approx_local_boundary_full_shape_scale: bool = False
    """If True with approximate local boundary updates, scale each local boundary
    shard using the full parameter shape rather than the local shard shape. This
    remains approximate but is closer to exact Muon update scaling.
    """

    muon_fsdp_approx_local_boundary_exclude_qkv: bool = False
    """If True with approximate local boundary updates, keep split-QKV boundary
    tensors on the exact gather path.
    """

    muon_fsdp_approx_local_boundary_max_local_numel: int = 0
    """If greater than zero with approximate local boundary updates, only approximate
    boundary tensors whose rank-consistent maximum original local shard has at most
    this many elements; larger local boundary shards keep the exact gather path.
    """

    muon_fsdp_approx_local_boundary_global_norm_scale: bool = False
    """If True with approximate local boundary updates, scale each local boundary
    update by the local/global pre-Newton-Schulz Frobenius norm ratio. This keeps
    the block-local approximation but avoids local-only norm amplification.
    """

    muon_fsdp_approx_local_boundary_foreach_norm: bool = False
    """If True, compute approximate local-boundary global-norm local norms with
    torch foreach norm when available. This preserves the scaling formula while
    reducing per-parameter reduction launch overhead.
    """

    muon_fsdp_approx_local_boundary_flat_norm_all_reduce: bool = False
    """If True, compute approximate local-boundary global-norm sums with one
    equivalent flat FSDP all-reduce when the DTensor plan exposes a flat shard
    group. This preserves the norm-ratio formula up to FP32 reduction order.
    """

    muon_fsdp_approx_local_boundary_async_norm_all_reduce: bool = False
    """If True, launch approximate local-boundary global-norm all-reduces on the
    Muon FSDP communication stream and wait only when the norm ratios are needed.
    This preserves the norm-ratio formula and only changes stream scheduling.
    """

    muon_fsdp_batched_qkv_local_boundary: bool = False
    """If True, allow split-QKV tensors on the approximate local-boundary path
    to use the batched split-QKV Newton-Schulz path when their local shard layout
    is eligible. This remains opt-in because local boundary QKV shards may not be
    aligned to full QKV split groups.
    """

    muon_fsdp_overlap_local_ns_first: bool = False
    """If True, prioritize fully local Newton-Schulz/update work before distributed
    Newton-Schulz work while overlapped boundary all-gathers are pending.
    """

    muon_fsdp_overlap_comm_compute: bool = False
    """If True, overlap Muon+M-FSDP boundary all-gathers with local Newton-Schulz/update work.
    Requires batched all-gather to take effect. Defaults to False.
    """

    muon_fsdp_overlap_boundary_ready_event: bool = False
    """If True, overlapped Muon+M-FSDP boundary gathers wait on an event recorded after
    boundary pre-NS tensors are ready instead of waiting on later unrelated default-stream work.
    This preserves the optimizer math and only changes scheduling. Defaults to False.
    """

    muon_fsdp_overlap_boundary_prefetch_batches: int = 1
    """Number of Muon+M-FSDP boundary gather batches to keep queued during overlap.
    Values above 1 use distinct gather scratch scopes to double-buffer communication
    and reduce gaps between NCCL all-gathers. The math is unchanged.
    """

    muon_fsdp_overlap_boundary_post_compute_prefetch_batches: int = 0
    """Target Muon+M-FSDP boundary gather queue depth after local/distributed under-gather
    Newton-Schulz work finishes. This keeps the initial prefetch depth conservative while
    allowing the boundary drain loop to queue more communication. A value of 0 disables
    the top-up. The optimizer math is unchanged.
    """

    muon_fsdp_overlap_boundary_progress_during_local: bool = False
    """If True, poll the oldest queued Muon+M-FSDP boundary gather between batched local
    Newton-Schulz chunks and start the next gather batch when it is complete. This only
    changes scheduling and preserves the optimizer math.
    """

    muon_fsdp_overlap_defer_boundary_batch_size: int = 1
    """Minimum same-key completed Muon+M-FSDP boundary updates to collect before applying
    them during overlap. A value of 1 applies completed boundary updates immediately.
    """

    muon_fsdp_batched_newton_schulz: bool = False
    """If True, batch same-shaped Muon+M-FSDP Newton-Schulz updates to reduce small-kernel
    launch overhead. Defaults to False.
    """

    muon_fsdp_batched_newton_schulz_max_numel: int = 16 * 1024 * 1024
    """Maximum elements in one pre-NS tensor eligible for batched Muon+M-FSDP Newton-Schulz."""

    muon_fsdp_batched_newton_schulz_max_batch_bytes: int = 2 * 1024 * 1024 * 1024
    """Approximate maximum input bytes per batched Muon+M-FSDP Newton-Schulz chunk."""

    muon_fsdp_batched_distributed_newton_schulz_max_batch_bytes: int = 0
    """Approximate maximum Gram bytes per batched distributed Muon+M-FSDP Newton-Schulz
    chunk. A value of 0 reuses muon_fsdp_batched_newton_schulz_max_batch_bytes.
    """

    muon_fsdp_foreach_pre_ns: bool = False
    """If True, compute Muon+M-FSDP local pre-Newton-Schulz momentum/Nesterov
    tensors with torch foreach elementwise kernels when the common decoupled
    weight-decay path is eligible. Defaults to False.
    """

    muon_fsdp_foreach_weight_update: bool = False
    """If True, apply batched Muon+M-FSDP local/distributed weight updates with torch foreach
    kernels when the updates share dtype, shape, and learning rate. Defaults to False.
    """

    muon_fsdp_foreach_gather_weight_update: bool = False
    """If True, also use torch foreach for eligible gather-mode Muon+M-FSDP weight updates after
    slicing each full orthogonalized update back to the local FSDP shard. Defaults to False.
    """

    # Lion.
    lion_beta1: float = 0.95
    """First beta coefficient for Lion optimizer (used in sign update). Defaults to 0.95."""

    lion_beta2: float = 0.98
    """Second beta coefficient for Lion optimizer (used in momentum EMA update).
    Defaults to 0.98."""

    soap_shampoo_beta: float = 0.95
    """The beta parameter for the Shampoo preconditioner."""

    soap_precondition_frequency: int = 1
    """The frequency of the Shampoo preconditioner."""

    soap_use_kl_shampoo: bool = True
    """Whether to use the KL-Shampoo preconditioner."""

    adaptive_muon_moment2_method: str = "adamuon"
    """The method to use for the moment2 update in Adaptive Muon optimizer."""

    adaptive_muon_beta2: float = 0.95
    """The beta2 parameter for the Adaptive Muon optimizer."""

    adaptive_muon_eps: float = 1e-8
    """The eps parameter for the Adaptive Muon optimizer."""

    #######################
    # Distributed optimizer
    #######################
    use_distributed_optimizer: bool = False
    """Distribute optimizer state over data-parallel replicas."""

    use_layer_wise_distributed_optimizer: bool = False
    """Use :class:`LayerWiseDistributedOptimizer` for emerging optimizers (e.g. Muon).
    When set via ``--use-distributed-optimizer`` with an emerging optimizer, the training
    arguments layer sets this flag and resets ``use_distributed_optimizer`` to False so
    that the standard distributed-optimizer path is not triggered."""

    overlap_param_gather: bool = False
    """If true, overlap param all-gather with forward compute. 
        This argument is intended to have the same value as the "overlap_param_gather" argument 
        in the "distributed_data_parallel_config.py" file. In the optimizer, this argument is 
        only used when "reuse_grad_buf_for_mxfp8_param_ag=True & fp8_param_gather=True".
    """

    overlap_param_gather_with_optimizer_step: bool = False
    """If true, overlap param all-gather of first bucket with optimizer step."""

    #######################
    # Optimizer Offload
    #######################

    optimizer_cpu_offload: bool = False
    """If True, offload optimizer states tensor and compute to CPU."""

    optimizer_offload_fraction: float = 0.0
    """Specifies the fraction of optimizer states to offload from GPU memory to CPU."""

    use_torch_optimizer_for_cpu_offload: bool = False
    """If True, use torch.optim.Optimizer for CPU offload."""

    overlap_cpu_optimizer_d2h_h2d: bool = False
    """
    When set to `True`, this flag enables overlapping of the CPU optimizer
    update process with the data transfer operations. This can help improve
    overall training efficiency by reducing idle time during data movement,
    allowing the optimizer to perform updates while gradients and parameters
    are being transferred between devices.
    """

    pin_cpu_grads: bool = True
    """If True, pin the optimizer gradients to CPU memory."""

    pin_cpu_params: bool = True
    """If True, pin the optimizer parameters to CPU memory."""

    ################
    # Miscellaneous
    ################
    clip_grad: float = 1.0
    """Gradient clipping based on global L2 norm."""

    log_num_zeros_in_grad: bool = False
    """If true, calculate and log the number of zeros in gradient."""

    barrier_with_L1_time: bool = False
    """If true, use barrier with level 1 time measurements."""

    timers: Optional[Callable] = None
    """Function to get timers."""

    config_logger_dir: str = ""
    """When non-empty, dumps entry-point configs to config_logger_dir"""

    optimizer_cuda_graph: bool = False
    """If true, enables CUDA graph for optimizer step."""

    def __post_init__(self):
        """Check the validity of the config."""

        # The following condition is used to avoid repetition in distrib_optimizer.py.
        # This is because in distrib_optimizer.py, the process to handle parameters are
        # different for different training precision settings. FP8 cases require different
        # handling while FP8 delayed scaling is an exception because the Adam optimizer in
        # TransformerEngine supports it in the kernel computation.
        # This is also the flag to determine the usage of param.grad or param.decoupled_grad
        self.use_precision_aware_optimizer_no_fp8_or_ds_fp8 = (
            self.use_precision_aware_optimizer
            and (
                self.main_params_dtype != torch.float32
                or (self.fp8_recipe is None or self.fp8_recipe == "delayed")
                or self.optimizer_cpu_offload
            )
        )

        if self.fp8_recipe == "mxfp8":
            if not self.reuse_grad_buf_for_mxfp8_param_ag:
                import warnings

                warnings.warn(
                    "mxfp8 without using reuse_grad_buf_for_mxfp8_param_ag and fp8_param_gather"
                    "will use significant amount additional GPU memory."
                    "Setting --reuse-grad-buf-for-mxfp8-param-ag and --fp8-param-gather is "
                    "recommended for mxfp8 training."
                )

        if self.use_precision_aware_optimizer:
            assert self.optimizer in (
                'adam',
                'muon',
            ), '--use-precision-aware-optimizer only supported with adam or muon'
            assert (
                self.use_distributed_optimizer
            ), '--use-precision-aware-optimizer only supported with distributed optimizer'

            if not is_te_min_version("2.1.0"):
                self.store_param_remainders = False

            # Only the FusedAdam in TE and HybridDeviceOptimizer supports
            # --use-precision-aware-optimizer.
            # TODO: Remove this check when apex's FusedAdam is no longer used.
            if self.optimizer_cpu_offload:
                return
            try:
                import inspect

                # TODO: Move this below?
                from transformer_engine.pytorch.optimizers import FusedAdam as Adam

                adam_args = inspect.signature(Adam).parameters
                arg_names = [
                    'master_weight_dtype',
                    'exp_avg_dtype',
                    'exp_avg_sq_dtype',
                    'use_decoupled_grad',
                ]
                for name in arg_names:
                    assert name in adam_args, (
                        "Current FusedAdam of TE doesn't support --use-precision-aware-optimizer, "
                        "please update TE version."
                    )
            except ImportError:
                raise RuntimeError(
                    '--use-precision-aware-optimizer requires FusedAdam from TransformerEngine, '
                    'but not found.'
                )
        else:
            assert (
                self.main_grads_dtype == torch.float32
            ), "main_grads_dtype can only be fp32 when not using precision-aware optimizer"
            assert (
                self.main_params_dtype == torch.float32
            ), "main_params_dtype can only be fp32 when not using precision-aware optimizer"
            assert (
                self.exp_avg_dtype == torch.float32
            ), "exp_avg_dtype can only be fp32 when not using precision-aware optimizer"
            assert (
                self.exp_avg_sq_dtype == torch.float32
            ), "exp_avg_sq_dtype can only be fp32 when not using precision-aware optimizer"


# Backward-compatible aliases (deprecated; use OptimizerConfig directly).
AdamOptimizerConfig = OptimizerConfig
SGDOptimizerConfig = OptimizerConfig
